--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzli/ServerEconomyPlayerMoney
build-by-default: true
branches:
- main
projects:
  ServerEconomyPlayerMoney:
    path: ""
    PHPStan: false
...
